AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 4.0.3
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false

plugins:
  - rubocop-rspec