services:
  postgres:
    image: postgres:18
    container_name: guess-anything-db
    restart: unless-stopped
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
