---
openapi: 3.1.2
info:
  title: Guess Anything
servers:
  - url: TBI
    description: Production server
tags:
  - name: Users
    description: User related routes
paths:
  /users:
    post:
      operationId: guess-anything.users.post
      description: Create a user
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - data
              properties:
                data:
                  type: object 
                  required: 
                    - username 
                    - mailAddress 
                    - password
                  properties: 
                    username: 
                      type: string 
                    mailAddress: 
                      type: string  
                    password: 
                      type: string
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    type: object 
                    required: 
                      - id 
                      - username
                      - mailAddress
                      - createdAt
                    properties: 
                      id:
                        type: string
                      username:
                        type: string
                      mailAddress:
                        type: string
                      createdAt:
                        type: string
        401:
          description: Unauthorized