---
openapi: 3.1.2
info:
  title: Service Name
servers:
  - url: TBI
    description: Production server
tags:
  - name: Users
    description: User related routes
paths:
  /users:
    post:
      operationId: service-name.users.post
      description: Create a user
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - data
              properties:
                data:
                  type: object
                  required:
                    - username
                    - mailAddress
                    - password
                  properties:
                    username:
                      type: string
                      maximum: 20
                    mailAddress:
                      type: string
                      format: email
                      maximum: 100
                    password:
                      type: string
                      format: password
                      maximum: 30
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    type: object
                    required:
                      - id
                      - username
                      - mailAddress
                      - createdAt
                    properties:
                      id:
                        type: string
                      username:
                        type: string
                      mailAddress:
                        type: string
                      createdAt:
                        type: string
        400:
          description: Bad Request
        401:
          description: Unauthorized
        409:
          description: Conflict
